name: Build all in one image

on:
  push:
    branches:
      - main
      - develop
  release:
    types: [published]

env:
  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
  DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set build args
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "BUILD_SBE_BRANCH=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            echo "BUILD_BE_BRANCH=main" >> $GITHUB_ENV
            echo "BUILD_FE_BRANCH=main" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "BUILD_SBE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "BUILD_BE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "BUILD_FE_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Set FE_BRANCH
        run: |
          echo "FE_BRANCH=${{ github.event_name == 'release' && 'main' || 'develop' }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: illacloud/build-all-in-one-image
          path: build-all-in-one-image

      - name: Build Docker Image
        run: |
          cd ./build-all-in-one-image
          docker build -f ./dockerfile -t illasoft/illa-builder:${IMAGE_TAG} --build-arg FE=${BUILD_FE_BRANCH} --build-arg BE=${BUILD_BE_BRANCH} --build-arg SBE=${BUILD_SBE_BRANCH} --no-cache .

      - name: Push Docker image
        run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
          docker push illasoft/illa-builder:${IMAGE_TAG}

      - name: Release Docker image
        if: github.event_name == 'release' &&
          startsWith(github.event.release.tag_name, 'illa-supervisor-backend v')
        run: |
          docker tag illasoft/illa-builder:${IMAGE_TAG} illasoft/illa-builder:latest
          docker push illasoft/illa-builder:latest
